### ISSUE TITLE
Support methods accepting Exception

### ISSUE THREAD

**Issue by abatishchev** [aelij/AsyncFriendlyStackTrace#1]
Hi, thanks for great tool!

However it doesn't play that nicely with a logging method accepting Exception, such as [TelemetryClient.TrackException(Exception)](https://msdn.microsoft.com/en-us/library/microsoft.applicationinsights.telemetryclient.trackexception.aspx).

Here's my current workaround:

``` csharp
    telemetryClient.TrackException(new Exception(context.Exception.ToAsyncString()));
```

But could be there a better way? For instance, reconstruct the actual, initial type of the exception.

**Comment by aelij** [comment]
Yes, I can see that could be a problem. Unfortunately the current public API of Application Insights doesn't seem to allow using this library. However the SDK is open-source, so you could open an issue there:

https://github.com/Microsoft/ApplicationInsights-dotnet

Looking at their code (`ExceptionConverter` class), they convert exceptions into their own serializable data format. They go through the `StackFrame`s. I think you could probably ask for an extensibility point there, to either filter frames or provide the entire serialized structure.

I would not use the workaround you suggested, as it puts the entire stack trace into the exception's Message property. I imagine the formatting on AI's website would not be great.

**Comment by Giorgi** [comment]
A possible solution is to create a new subclass from Exception, override StackTrace property and return async friendly stacktrace. Something like `StackTraceExtensions.ToAsyncFriendlyException(exception)`

**Comment by abatishchev** [comment]
@Giorgi good shot! The only drawback is that the initial exception type is missing now.

**Comment by Giorgi** [comment]
@abatishchev We can pass the initial exception as an inner exception so detailed info will be available too. We can also include exception type in message for the new exception.

**Comment by abatishchev** [comment]
This is near-to-exactly what I'm doing so just decided to check any other options if any.

**Comment by aelij** [comment]
@Giorgi, that won't work for Application Insights because they use the StackTrace class to break down the stack frames and not the StackTrace property.

**Comment by abatishchev** [comment]
Bummer. Could you please suggest the best approach so far?

**Comment by aelij** [comment]
I was just writing a comment... I don't think it can be done. Especially in App Insights.
