### ISSUE TITLE
Signing problems in version 1.3 and 1.4

### ISSUE THREAD

**Issue by rasmus-s** [aelij/AsyncFriendlyStackTrace#10]
Problems when upgrade to version 1.3 or 1.4 i get this runtime exception:

`Could not load file or assembly 'AsyncFriendlyStackTrace, Version=1.4.0.0, Culture=neutral, PublicKeyToken=f5fdf019656607c4' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)`

Looks like a signing issue, and sn.exe also say that the assembly is not valid:

> C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Bin>sn -vf C:\Temp\AsyncFriendlyStackTrace.1.4.0\lib\net45\AsyncFriendlyStackTrace.dll
> 
> Microsoft (R) .NET Framework Strong Name Utility  Version 3.5.30729.1
> Copyright (c) Microsoft Corporation.  All rights reserved.
> 
> Failed to verify assembly -- Strong name validation failed for assembly 'C:\Temp\AsyncFriendlyStackTrace.1.4.0\lib\net45\AsyncFriendlyStackTrace.dll'.

Running .net 4.5.1

**Comment by aelij** [comment]
Hi. How are you getting this error? I've tried loading the assembly from another strongly signed assembly and it worked. I'm not sure how signing works in project.json projects.

**Comment by rasmus-s** [comment]
Hi, Im not using project.json project, but a normal .net project 4.5.1 in Visual studio 2015. Our project and libs are not signed. I had tried to remove the publicKey from my project reference to your AsyncFriendlyStackTrace.dll but with out help, it look like the runtime want to check/validate the assembly it loads.

**Comment by aelij** [comment]
Can you produce a repro? It works for me.

**Comment by rasmus-s** [comment]
Its our xunit test that throw this exception, and we had not problems with other 3rd party libs that also is signet in our test. 

Here is the test class:

```
public class TestClass
{
    [Fact]
    public void Test()
    {
        try
        {
            ThrowExceptionMethod().Wait();
        }
        catch (Exception e)
        {
            var str = e.ToAsyncString();
        }
    }

    private static async Task ThrowExceptionMethod()
    {
        await Task.Run(() =>
        {
            throw new Exception("fdsf");
        });
    }
}
```

With hint from this [github issue](https://github.com/dotnet/roslyn/issues/6052) i disabled shadow-copy in reshapper and then the test pass. But why is your assembly special? we had over 40 other nuget reference and many of them is signet and had no issues when run them from xunit.

**Comment by bbbush** [comment]
Thanks for the good work. Unfortunately I see the same warning.

```
1>------ Publish started: Project: XXXAPI, Configuration: Debug Any CPU ------
1>Connecting to D:\inetpub\wwwroot\XXXAPI...
1>Copying all files to temporary location below for package/publish:
1>obj\Debug\AspnetCompileMerge\Source.
1>C:\Windows\Microsoft.NET\Framework\v4.0.30319\aspnet_compiler.exe -v \ -p D:\XXX\obj\Debug\AspnetCompileMerge\Source -u -c D:\XXX\obj\Debug\AspnetCompileMerge\TempBuildDir 
1>ASPNETCOMPILER(0,0): Error ASPCONFIG: Could not load file or assembly 'AsyncFriendlyStackTrace, Version=1.4.0.0, Culture=neutral, PublicKeyToken=f5fdf019656607c4' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
1>
========== Build: 0 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========
```

**Comment by aelij** [comment]
Hmm. Not sure what to make of this. Can anyone please try compiling the project and verifying the problem still exists?

**Comment by rasmus-s** [comment]
@aelij when you have merged and released a new nuget package, let me know in this thread.

**Comment by aelij** [comment]
The package has been pushed (v1.4.1). Thanks everyone.
