### ISSUE TITLE
Filter out ExceptionDispatchInfo.Throw()

### ISSUE THREAD

**Issue by adamhathcock** [aelij/AsyncFriendlyStackTrace#13]
I get this all the time: `at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()`

Can you add an option to filter it?  Might be .NET Core specific.

**Comment by aelij** [comment]
Dup of #12

**Comment by adamhathcock** [comment]
Oops, didn't actually read the other issue.  Sorry!

**Comment by aelij** [comment]
No problem. I usually use the search box under issues before opening a new one. Searching for `ExceptionDispatchInfo` would've found the dup in this case :)
