### ISSUE TITLE
Handling of Task.Run() with anonymous Action/Func

### ISSUE THREAD

**Issue by nicolaihenriksen** [aelij/AsyncFriendlyStackTrace#15]
Hi Eli

Cool stuff you got here! Trims away a lot of the (in most cases) unnecessary junk from logfiles. I have, however, encountered a scenario which is not supported that well. I'll leave it to you to decide whether it is a bug or not.

Consider the following example code illustrating the issue:
```C#
class Program
{
    static void Main(string[] args)
    {
        try
        {
            MyMethodAsync().Wait();
        }
        catch (Exception e)
        {
            var s1 = e.ToString();
            var s2 = e.ToAsyncString();
        }
    }

    private static async Task MyMethodAsync()
    {
        await Task.Run(async () =>
        {
            await Task.Run(() =>
            {
                MethodThrowingException();
            });
        });
    }

    private static void MethodThrowingException()
    {
        throw new NotImplementedException("Testing!");
    }
}
```

The value of _s2_ in the catch block of _Main()_ will have an inner exception (#0) trace like this:

> ---> (Inner Exception #0) System.NotImplementedException: Testing!
   at AsyncStacktraceTesting.Program.MethodThrowingException() in C:\Users\nche\Documents\AsyncStacktraceTesting\AsyncStacktraceTesting\Program.cs:line 38
   at AsyncStacktraceTesting.Program.<>c.<MyMethodAsync>b__1_1() in C:\Users\nche\Documents\AsyncStacktraceTesting\AsyncStacktraceTesting\Program.cs:line 31
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at async AsyncStacktraceTesting.Program.<>c.<MyMethodAsync>b__1_0(?) in C:\Users\nche\Documents\AsyncStacktraceTesting\AsyncStacktraceTesting\Program.cs:line 29
   at async AsyncStacktraceTesting.Program.MyMethodAsync(?) in C:\Users\nche\Documents\AsyncStacktraceTesting\AsyncStacktraceTesting\Program.cs:line 27<---

As you can see, the anonymous action executing on line 29 is actually recognized as **async**, while the anonymous action on line 31 is not. Also the formatting of the method name could perhaps be improved, in such a case, while you're at it; not sure what it could be other than perhaps "anonymous" or something (perhaps Action or Func if you're able to differentiate) :-)

Like I said, I'm not even sure this is a defect or whether you have explicitly stated that this is not supported. But have a look and do what you want with it.

**Comment by aelij** [comment]
Hi @nicolaihenriksen 

Line 31 is not in an async lambda, that's why there's no `async` indication in the stack trace.

I'd rather not change the way lambdas are rendered because it would be hard to locate the actual method (e.g. using a decompiler). In contrast, async methods do map well to code, so removing `MoveNext` makes sense there.

You may also find [ben's work](https://twitter.com/ben_a_adams/status/924750286132006913) interesting.

**Comment by nicolaihenriksen** [comment]
Ha! You're right. I had tried too many things and ended up confusing myself. Of course it is not an async lambda (it was, but I removed it again). Sorry about that!

Fair enough about the lambda rendering.

I'll look into what Ben is doing. Thanks for the link!
