### ISSUE TITLE
Support been able to project the stacktrace onto just one line

### ISSUE THREAD

**Issue by ymor** [aelij/AsyncFriendlyStackTrace#16]
When logging exceptions to services such as ELK, it would be useful for the async friendly stack trace to be spat out on one line instead of multiple.  Otherwise this creates a log event per new line.

**Comment by aidapsibr** [comment]
Have you had a look at this? https://sematext.com/blog/handling-stack-traces-with-logstash/

**Comment by aelij** [comment]
Closing as this could be handled by a log processor.
