### ISSUE TITLE
System.ArgumentException: Instance field 'stack_trace' is not defined for type 'System.Exception' when running on mono

### ISSUE THREAD

**Issue by pruiz** [aelij/AsyncFriendlyStackTrace#17]
Hi,

Since mono has been incorporating MS.NET source bits here and there, it looks like the reflection trick in order to obtain the internal field holding the stacktrace, no longer works in recent mono versions (at least on 5.8.x).

It looks like AsyncFriendlyStackTrace needs to be updated to try to guess wether Exception contains a field stack_trace, and if not, simply assume MS.NET field name instead.

**Comment by aelij** [comment]
Care to submit a PR? :)

**Comment by pruiz** [comment]
Sure..

**Comment by pruiz** [comment]
Submitted pull-req with fix for this issue.

**Comment by aelij** [comment]
Pushed v1.6.0 to NuGet.

**Comment by pruiz** [comment]
Kool! thnks ;)
