### ISSUE TITLE
"Instance field '_stackTraceString' is not defined" under linux/mono

### ISSUE THREAD

**Issue by saxx** [aelij/AsyncFriendlyStackTrace#3]
Under Linux/Mono, I get this exception:

```
System.TypeInitializationException: An exception was thrown by the type initializer for AsyncFriendlyStackTrace.ExceptionExtensions ---> System.ArgumentException: Instance field '_stackTraceString' is not defined for type 'System.Exception'
  at System.Linq.Expressions.Expression.Field (System.Linq.Expressions.Expression expression, System.String fieldName) [0x00000] in <filename unknown>:0 
  at AsyncFriendlyStackTrace.ReflectionUtil.GenerateGetField[Exception,String] (System.String fieldName) [0x00000] in <filename unknown>:0 
  at AsyncFriendlyStackTrace.ExceptionExtensions..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
```

I imagine that the internal implementation of System.Exception in Mono is different than the "original" .NET implementation. I took a look at the sources, maybe it can be fixed using `Exception.ToString()` to get an exceptions stack trace, instead of using a private field? But I'm not sure about the `RemoteStackTrace`? (I don't even know what's this supposed to be, that's why I didn't submit a PR in the first place).

**Comment by aelij** [comment]
`ToString()` would not be good, as it doesn't contain just the stack trace, but also the message and inner stack traces.

The `_stackTraceString` field stores exception stack trace after deserialization. I just looked in Mono's [sources](https://github.com/mono/mono/blob/master/mcs/class/corlib/System/Exception.cs), it seems the field's name is slightly different - `stack_trace`. Feel free to submit a PR with an `#if MONO` to contain this difference. Thanks!

`RemoteStackTrace` is used in .NET for `RealProxy` invocations. From what I can see, this is still the same in Mono (`_remoteStackTraceString`).
