### ISSUE TITLE
Unable to resolve dependency 'NETStandard.Library'

### ISSUE THREAD

**Issue by daniellittledev** [aelij/AsyncFriendlyStackTrace#9]
I tried to install the package in a `.net 4.5.2` project but it was unable to install.

Failed with the message:

```
Unable to resolve dependency 'NETStandard.Library'. 
Source(s) used: 'api.nuget.org (v3)', 'nuget.org', 'Microsoft and .NET'.
```

**Comment by aelij** [comment]
Thanks, I've released the package for .NET Core RTM and fixed this issue.
